import type { CanvasNode } from "./scene";

const styleToTailwind = (s: CanvasNode["style"]): string => {
  const cls: string[] = [];
  if (s.display === "flex") cls.push("flex");
  if (s.flexDirection === "column") cls.push("flex-col");
  if (s.alignItems === "center") cls.push("items-center");
  if (s.alignItems === "start") cls.push("items-start");
  if (s.alignItems === "end") cls.push("items-end");
  if (s.justifyContent === "center") cls.push("justify-center");
  if (s.justifyContent === "between") cls.push("justify-between");
  return cls.join(" ");
};

const inlineStyle = (n: CanvasNode): string => {
  const s = n.style;
  const parts: string[] = [
    `width: '${n.size.width}px'`,
    `height: '${n.size.height}px'`,
  ];
  if (s.background) parts.push(`background: '${s.background}'`);
  if (s.color) parts.push(`color: '${s.color}'`);
  if (s.borderRadius) parts.push(`borderRadius: '${s.borderRadius}px'`);
  if (s.borderWidth)
    parts.push(`border: '${s.borderWidth}px solid ${s.borderColor ?? "#000"}'`);
  if (s.padding) parts.push(`padding: '${s.padding}px'`);
  if (s.fontSize) parts.push(`fontSize: '${s.fontSize}px'`);
  if (s.fontWeight) parts.push(`fontWeight: ${s.fontWeight}`);
  return `{${parts.join(", ")}}`;
};

const renderNode = (n: CanvasNode, indent = 4): string => {
  const pad = " ".repeat(indent);
  const cls = styleToTailwind(n.style);
  const clsAttr = cls ? ` className="${cls}"` : "";
  const style = ` style={${inlineStyle(n)}}`;

  switch (n.type) {
    case "text":
      return `${pad}<p${clsAttr}${style}>${n.content ?? ""}</p>`;
    case "button":
      return `${pad}<button${clsAttr}${style}>${n.content ?? ""}</button>`;
    case "input":
      return `${pad}<input${clsAttr}${style} placeholder="${n.content ?? ""}" />`;
    case "image":
      return `${pad}<div${clsAttr}${style} role="img" aria-label="image" />`;
    case "box":
    default:
      return `${pad}<div${clsAttr}${style} />`;
  }
};

export const generateCode = (nodes: CanvasNode[]): string => {
  const sorted = [...nodes].sort((a, b) => a.zIndex - b.zIndex);
  const body = sorted.map((n) => renderNode(n, 6)).join("\n");

  return `// Generated by DevCanvas — UI is the source of truth.
// Copilot:
// - Wire up event handlers
// - Add data fetching
// - Add validation & error states

export default function GeneratedPage() {
  return (
    <div className="relative min-h-screen bg-background text-foreground">
${body}
    </div>
  );
}
`;
};
