import type { CanvasNode, Page } from "./scene";

const styleToTailwind = (s: CanvasNode["style"]): string => {
  const cls: string[] = [];
  if (s.display === "flex") cls.push("flex");
  if (s.flexDirection === "column") cls.push("flex-col");
  if (s.alignItems === "center") cls.push("items-center");
  if (s.alignItems === "start") cls.push("items-start");
  if (s.alignItems === "end") cls.push("items-end");
  if (s.justifyContent === "center") cls.push("justify-center");
  if (s.justifyContent === "between") cls.push("justify-between");
  return cls.join(" ");
};

const inlineStyle = (n: CanvasNode): string => {
  const s = n.style;
  const parts: string[] = [
    `position: 'absolute'`,
    `left: '${Math.round(n.position.x)}px'`,
    `top: '${Math.round(n.position.y)}px'`,
    `width: '${n.size.width}px'`,
    `height: '${n.size.height}px'`,
  ];
  if (s.background) parts.push(`background: '${s.background}'`);
  if (s.color) parts.push(`color: '${s.color}'`);
  if (s.borderRadius) parts.push(`borderRadius: '${s.borderRadius}px'`);
  if (s.borderWidth)
    parts.push(`border: '${s.borderWidth}px solid ${s.borderColor ?? "#000"}'`);
  if (s.padding) parts.push(`padding: '${s.padding}px'`);
  if (s.fontSize) parts.push(`fontSize: '${s.fontSize}px'`);
  if (s.fontWeight) parts.push(`fontWeight: ${s.fontWeight}`);
  return `{${parts.join(", ")}}`;
};

const renderNode = (n: CanvasNode, indent = 8): string => {
  const pad = " ".repeat(indent);
  const cls = styleToTailwind(n.style);
  const clsAttr = cls ? ` className="${cls}"` : "";
  const style = ` style={${inlineStyle(n)}}`;

  switch (n.type) {
    case "text":
      return `${pad}<p${clsAttr}${style}>${n.content ?? ""}</p>`;
    case "button":
      return `${pad}<button${clsAttr}${style}>${n.content ?? ""}</button>`;
    case "input":
      return `${pad}<input${clsAttr}${style} placeholder="${n.content ?? ""}" />`;
    case "image":
      return `${pad}<div${clsAttr}${style} role="img" aria-label="image" />`;
    case "box":
    default:
      return `${pad}<div${clsAttr}${style} />`;
  }
};

const componentName = (name: string) =>
  name
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .split(" ")
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("") || "Page";

export const generateCode = (nodes: CanvasNode[], pages: Page[] = []): string => {
  if (pages.length === 0) {
    const sorted = [...nodes].sort((a, b) => a.zIndex - b.zIndex);
    const body = sorted.map((n) => renderNode(n, 6)).join("\n");
    return `// Generated by DevCanvas
export default function GeneratedPage() {
  return (
    <div className="relative min-h-screen bg-background text-foreground">
${body}
    </div>
  );
}
`;
  }

  const pageBlocks = pages
    .map((page) => {
      const pageNodes = nodes
        .filter((n) => n.pageId === page.id)
        .sort((a, b) => a.zIndex - b.zIndex);
      const body = pageNodes.map((n) => renderNode(n, 6)).join("\n");
      return `// ----- ${page.name} -----
// Copilot: wire handlers, fetch data, add validation.
export function ${componentName(page.name)}() {
  return (
    <div className="relative" style={{ width: ${page.size.width}, height: ${page.size.height}, background: '${page.background ?? "#0f0d0b"}' }}>
${body}
    </div>
  );
}`;
    })
    .join("\n\n");

  return `// Generated by DevCanvas — UI is the source of truth.
// ${pages.length} page${pages.length === 1 ? "" : "s"} · ${nodes.length} elements
${pageBlocks}
`;
};
